// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marzipanstate.proto

#ifndef PROTOBUF_INCLUDED_marzipanstate_2eproto
#define PROTOBUF_INCLUDED_marzipanstate_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_marzipanstate_2eproto 

namespace protobuf_marzipanstate_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_marzipanstate_2eproto
class FractalProto;
class FractalProtoDefaultTypeInternal;
extern FractalProtoDefaultTypeInternal _FractalProto_default_instance_;
namespace google {
namespace protobuf {
template<> ::FractalProto* Arena::CreateMaybeMessage<::FractalProto>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class FractalProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FractalProto) */ {
 public:
  FractalProto();
  virtual ~FractalProto();

  FractalProto(const FractalProto& from);

  inline FractalProto& operator=(const FractalProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FractalProto(FractalProto&& from) noexcept
    : FractalProto() {
    *this = ::std::move(from);
  }

  inline FractalProto& operator=(FractalProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FractalProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FractalProto* internal_default_instance() {
    return reinterpret_cast<const FractalProto*>(
               &_FractalProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(FractalProto* other);
  friend void swap(FractalProto& a, FractalProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FractalProto* New() const final {
    return CreateMaybeMessage<FractalProto>(NULL);
  }

  FractalProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FractalProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FractalProto& from);
  void MergeFrom(const FractalProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FractalProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double top = 1;
  void clear_top();
  static const int kTopFieldNumber = 1;
  double top() const;
  void set_top(double value);

  // double bottom = 2;
  void clear_bottom();
  static const int kBottomFieldNumber = 2;
  double bottom() const;
  void set_bottom(double value);

  // double left = 3;
  void clear_left();
  static const int kLeftFieldNumber = 3;
  double left() const;
  void set_left(double value);

  // double right = 4;
  void clear_right();
  static const int kRightFieldNumber = 4;
  double right() const;
  void set_right(double value);

  // uint32 width = 5;
  void clear_width();
  static const int kWidthFieldNumber = 5;
  ::google::protobuf::uint32 width() const;
  void set_width(::google::protobuf::uint32 value);

  // uint32 height = 6;
  void clear_height();
  static const int kHeightFieldNumber = 6;
  ::google::protobuf::uint32 height() const;
  void set_height(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:FractalProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double top_;
  double bottom_;
  double left_;
  double right_;
  ::google::protobuf::uint32 width_;
  ::google::protobuf::uint32 height_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_marzipanstate_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FractalProto

// double top = 1;
inline void FractalProto::clear_top() {
  top_ = 0;
}
inline double FractalProto::top() const {
  // @@protoc_insertion_point(field_get:FractalProto.top)
  return top_;
}
inline void FractalProto::set_top(double value) {
  
  top_ = value;
  // @@protoc_insertion_point(field_set:FractalProto.top)
}

// double bottom = 2;
inline void FractalProto::clear_bottom() {
  bottom_ = 0;
}
inline double FractalProto::bottom() const {
  // @@protoc_insertion_point(field_get:FractalProto.bottom)
  return bottom_;
}
inline void FractalProto::set_bottom(double value) {
  
  bottom_ = value;
  // @@protoc_insertion_point(field_set:FractalProto.bottom)
}

// double left = 3;
inline void FractalProto::clear_left() {
  left_ = 0;
}
inline double FractalProto::left() const {
  // @@protoc_insertion_point(field_get:FractalProto.left)
  return left_;
}
inline void FractalProto::set_left(double value) {
  
  left_ = value;
  // @@protoc_insertion_point(field_set:FractalProto.left)
}

// double right = 4;
inline void FractalProto::clear_right() {
  right_ = 0;
}
inline double FractalProto::right() const {
  // @@protoc_insertion_point(field_get:FractalProto.right)
  return right_;
}
inline void FractalProto::set_right(double value) {
  
  right_ = value;
  // @@protoc_insertion_point(field_set:FractalProto.right)
}

// uint32 width = 5;
inline void FractalProto::clear_width() {
  width_ = 0u;
}
inline ::google::protobuf::uint32 FractalProto::width() const {
  // @@protoc_insertion_point(field_get:FractalProto.width)
  return width_;
}
inline void FractalProto::set_width(::google::protobuf::uint32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:FractalProto.width)
}

// uint32 height = 6;
inline void FractalProto::clear_height() {
  height_ = 0u;
}
inline ::google::protobuf::uint32 FractalProto::height() const {
  // @@protoc_insertion_point(field_get:FractalProto.height)
  return height_;
}
inline void FractalProto::set_height(::google::protobuf::uint32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:FractalProto.height)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_marzipanstate_2eproto
